x = 'danielsadri01'
print(x[3])
print(x[-2])
print(x[3:11])
print(x[2:-3])
print(x[-5:-2])
print(x[:8])
print(x[3:])
print(x[0:3] + x[3:])
print(x[-4:])
print(x[0:13:2])
print(len(x))
print(x[len(x) - 1])
print(x[::-1])
